/**
 * Hermetic environment construction.
 *
 * The developer's real `~/.gitconfig`, their `/etc/gitconfig`, their proxy variables and
 * any ambient `GIT_*` state must not be able to change a test result. Every sandbox gets:
 *
 *   - `GIT_CONFIG_GLOBAL` pointing at a config file the sandbox owns,
 *   - `GIT_CONFIG_SYSTEM=/dev/null`,
 *   - `HOME`/`XDG_*` inside the sandbox,
 *   - `GIT_CEILING_DIRECTORIES` so repo discovery cannot walk out of the sandbox,
 *   - an allowlisted `PATH` and nothing else inherited.
 *
 * Nothing here reaches the network: "remotes" are local bare repos.
 */

import { realpathSync } from "node:fs";
import { tmpdir } from "node:os";

/**
 * The machine's real temp dir, captured at module load and realpath'd.
 *
 * Never call `os.tmpdir()` later: tests legitimately copy a sandbox's env (including
 * `TMPDIR`) into `process.env` so that in-process `src/*` calls are hermetic, and that
 * sandbox is deleted at the end of the test. Anything that read `os.tmpdir()` afterwards
 * would point at a directory that no longer exists.
 */
export const HOST_TMPDIR: string = realpathSync(tmpdir());

/** Identity forced on every commit made inside a sandbox. */
export const TEST_USER_NAME = "Overgit Test";
export const TEST_USER_EMAIL = "test@overgit.invalid";

/**
 * Fixed clock base (2021-01-01T00:00:00Z). `Repo.commit()` advances by one second per
 * commit so object ids are stable for a given sequence of operations.
 */
export const TEST_EPOCH = 1609459200;

/**
 * Contents of the sandbox's `GIT_CONFIG_GLOBAL` file.
 *
 * `advice.*` is turned off wherever git would otherwise print multi-line guidance that
 * makes stderr assertions brittle.
 */
export function globalGitConfig(): string {
  return `# generated by test/helpers/env.ts - do not edit
[user]
\tname = ${TEST_USER_NAME}
\temail = ${TEST_USER_EMAIL}
[init]
\tdefaultBranch = main
[commit]
\tgpgsign = false
[tag]
\tgpgsign = false
[core]
\tautocrlf = false
\tsafecrlf = false
\tquotepath = false
\tsymlinks = true
\tfsmonitor = false
\tuntrackedCache = false
\tpager = cat
\teditor = false
[gc]
\tauto = 0
[maintenance]
\tauto = false
[fetch]
\twriteCommitGraph = false
\tprune = false
[pull]
\trebase = false
[merge]
\tconflictStyle = merge
[rerere]
\tenabled = false
[protocol "file"]
\tallow = always
[safe]
\tdirectory = *
[log]
\tdate = iso
[status]
\trelativePaths = false
[advice]
\taddEmbeddedRepo = false
\taddIgnoredFile = false
\tdetachedHead = false
\tdiverging = false
\tignoredHook = false
\tpushNonFastForward = false
\tresolveConflict = false
\tsequencerInUse = false
\tskippedCherryPicks = false
\tstatusHints = false
\tstatusUoption = false
\tsubmoduleAlternateErrorStrategyDie = false
\tupdateSparsePath = false
\twaitingForEditor = false
`;
}

export interface SandboxEnvPaths {
  /** Sandbox root (already realpath'd). */
  dir: string;
  home: string;
  tmp: string;
  gitConfigPath: string;
  /** Directory git must not search above. */
  ceiling: string;
}

/**
 * Build the complete child environment. Nothing is inherited except `PATH` (and, on the
 * rare platform that needs them, the dynamic-loader variables).
 *
 * Deliberately absent: `HTTP_PROXY`/`HTTPS_PROXY`/`ALL_PROXY` (a LAN proxy would make
 * `file://` remotes behave strangely), and every ambient `GIT_DIR`/`GIT_WORK_TREE`/
 * `GIT_INDEX_FILE`/`GIT_OBJECT_DIRECTORY` that a wrapping git process might have set.
 */
export function buildSandboxEnv(
  paths: SandboxEnvPaths,
  extra: Record<string, string | undefined> = {},
): Record<string, string> {
  const env: Record<string, string> = {
    PATH: process.env.PATH ?? "/usr/local/bin:/usr/bin:/bin",
    HOME: paths.home,
    TMPDIR: paths.tmp,
    XDG_CONFIG_HOME: `${paths.home}/.config`,
    XDG_CACHE_HOME: `${paths.home}/.cache`,
    XDG_DATA_HOME: `${paths.home}/.local/share`,
    XDG_STATE_HOME: `${paths.home}/.local/state`,

    GIT_CONFIG_GLOBAL: paths.gitConfigPath,
    GIT_CONFIG_SYSTEM: "/dev/null",
    GIT_CEILING_DIRECTORIES: paths.ceiling,
    GIT_TERMINAL_PROMPT: "0",
    GIT_PAGER: "cat",
    PAGER: "cat",
    GIT_AUTHOR_NAME: TEST_USER_NAME,
    GIT_AUTHOR_EMAIL: TEST_USER_EMAIL,
    GIT_COMMITTER_NAME: TEST_USER_NAME,
    GIT_COMMITTER_EMAIL: TEST_USER_EMAIL,

    LC_ALL: "C",
    LANG: "C",
    TZ: "UTC",
    TERM: "dumb",
    COLUMNS: "80",
    NO_COLOR: "1",

    // Mark the process tree as a test run so the CLI can be defensive if it wants.
    OVERGIT_TEST: "1",
  };

  // macOS/Linux loaders occasionally need these; copy only when already present.
  for (const k of ["DYLD_LIBRARY_PATH", "LD_LIBRARY_PATH", "SYSTEMROOT"]) {
    const v = process.env[k];
    if (v) env[k] = v;
  }

  for (const [k, v] of Object.entries(extra)) {
    if (v === undefined) delete env[k];
    else env[k] = v;
  }
  return env;
}
